# Configuration MySQL / XAMPP
# Modifie ces valeurs selon ta configuration XAMPP locale

db.url=jdbc:mysql://localhost:3306/nexus_download?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
db.user=root
db.password=